// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddDevice(arg1:string,arg2:string):Promise<models.Device>;

export function BackupDevices(arg1:Array<string>,arg2:string,arg3:string):Promise<Array<models.BackupResult>>;

export function ClearDevices():Promise<void>;

export function ConfigureCamera(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<boolean|string>;

export function GetAllDevices():Promise<Array<models.Device>>;

export function GetBackupSettings():Promise<models.BackupSettings>;

export function GetCameraConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Camera>;

export function GetCameraTasks(arg1:string,arg2:string,arg3:string):Promise<Array<models.Camera>>;

export function GetCurrentRegion():Promise<string>;

export function GetDevices():Promise<Array<models.Device>>;

export function GetRegions():Promise<Array<string>>;

export function LoginToDevice(arg1:string,arg2:string,arg3:string):Promise<boolean|string>;

export function ParseExcelSheet(arg1:string,arg2:number):Promise<Array<models.ExcelRow>>;

export function ProcessExcelData(arg1:Array<models.ExcelRow>,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string):Promise<Array<models.CameraConfigResult>>;

export function RefreshDevices():Promise<Array<models.Device>>;

export function RemoveDevice(arg1:string):Promise<void>;

export function RestoreDevicesDB(arg1:Array<string>,arg2:string,arg3:string,arg4:string):Promise<Array<models.RestoreResult>>;

export function SaveBackupSettings(arg1:models.BackupSettings):Promise<void>;

export function SaveExcelData(arg1:string):Promise<string>;

export function ScanIPRange(arg1:string,arg2:string):Promise<Array<models.Device>>;

export function SetCameraIndex(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<boolean|string>;

export function SetDeviceRegion(arg1:string,arg2:string):Promise<void>;

export function SetDevicesRegion(arg1:Array<string>,arg2:string):Promise<void>;

export function SetRegionFilter(arg1:string):Promise<Array<models.Device>>;

export function SyncDeviceTime(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<models.TimeSyncResult>>;

export function UpdateDevicesFile(arg1:string,arg2:number):Promise<Array<models.UpdateResult>>;
