// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDevice(arg1, arg2) {
  return window['go']['main']['App']['AddDevice'](arg1, arg2);
}

export function BackupDevices(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BackupDevices'](arg1, arg2, arg3, arg4, arg5);
}

export function ClearDevices() {
  return window['go']['main']['App']['ClearDevices']();
}

export function ConfigureCamera(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ConfigureCamera'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetAllDevices() {
  return window['go']['main']['App']['GetAllDevices']();
}

export function GetBackupSettings() {
  return window['go']['main']['App']['GetBackupSettings']();
}

export function GetCameraConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetCameraConfig'](arg1, arg2, arg3, arg4);
}

export function GetCameraTasks(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCameraTasks'](arg1, arg2, arg3);
}

export function GetCurrentRegion() {
  return window['go']['main']['App']['GetCurrentRegion']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetRegions() {
  return window['go']['main']['App']['GetRegions']();
}

export function LoginToDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoginToDevice'](arg1, arg2, arg3);
}

export function ParseExcelSheet(arg1, arg2) {
  return window['go']['main']['App']['ParseExcelSheet'](arg1, arg2);
}

export function ProcessExcelData(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ProcessExcelData'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RefreshDevices() {
  return window['go']['main']['App']['RefreshDevices']();
}

export function RemoveDevice(arg1) {
  return window['go']['main']['App']['RemoveDevice'](arg1);
}

export function RestoreDevicesDB(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RestoreDevicesDB'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveBackupSettings(arg1) {
  return window['go']['main']['App']['SaveBackupSettings'](arg1);
}

export function SaveExcelData(arg1) {
  return window['go']['main']['App']['SaveExcelData'](arg1);
}

export function ScanIPRange(arg1, arg2) {
  return window['go']['main']['App']['ScanIPRange'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetCameraIndex(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetCameraIndex'](arg1, arg2, arg3, arg4, arg5);
}

export function SetDeviceRegion(arg1, arg2) {
  return window['go']['main']['App']['SetDeviceRegion'](arg1, arg2);
}

export function SetDevicesRegion(arg1, arg2) {
  return window['go']['main']['App']['SetDevicesRegion'](arg1, arg2);
}

export function SetRegionFilter(arg1) {
  return window['go']['main']['App']['SetRegionFilter'](arg1);
}

export function SyncDeviceTime(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncDeviceTime'](arg1, arg2, arg3);
}

export function UpdateDevicesFile(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateDevicesFile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
