// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDevice(arg1) {
  return window['go']['main']['App']['AddDevice'](arg1);
}

export function CleanupTempFiles() {
  return window['go']['main']['App']['CleanupTempFiles']();
}

export function ConfigureCamera(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ConfigureCamera'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ConfigureCameraWithToken(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ConfigureCameraWithToken'](arg1, arg2, arg3, arg4, arg5);
}

export function ConfigureCamerasFromData(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ConfigureCamerasFromData'](arg1, arg2, arg3, arg4, arg5);
}

export function GetCameraConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetCameraConfig'](arg1, arg2, arg3, arg4);
}

export function GetCameraConfigWithToken(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCameraConfigWithToken'](arg1, arg2, arg3);
}

export function GetCameraTasks(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCameraTasks'](arg1, arg2, arg3);
}

export function GetCameraTasksWithToken(arg1, arg2) {
  return window['go']['main']['App']['GetCameraTasksWithToken'](arg1, arg2);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetUploadFile() {
  return window['go']['main']['App']['GetUploadFile']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadDevices() {
  return window['go']['main']['App']['LoadDevices']();
}

export function LoginToDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoginToDevice'](arg1, arg2, arg3);
}

export function ParseExcelSheet(arg1, arg2) {
  return window['go']['main']['App']['ParseExcelSheet'](arg1, arg2);
}

export function ProcessExcelData(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ProcessExcelData'](arg1, arg2, arg3, arg4, arg5);
}

export function RefreshDevices() {
  return window['go']['main']['App']['RefreshDevices']();
}

export function RemoveDevice(arg1) {
  return window['go']['main']['App']['RemoveDevice'](arg1);
}

export function SaveDevices() {
  return window['go']['main']['App']['SaveDevices']();
}

export function SaveExcelData(arg1) {
  return window['go']['main']['App']['SaveExcelData'](arg1);
}

export function ScanIPRange(arg1, arg2) {
  return window['go']['main']['App']['ScanIPRange'](arg1, arg2);
}

export function SetCameraIndex(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetCameraIndex'](arg1, arg2, arg3, arg4, arg5);
}

export function SetCameraIndexWithToken(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetCameraIndexWithToken'](arg1, arg2, arg3, arg4);
}

export function SetUploadFile(arg1) {
  return window['go']['main']['App']['SetUploadFile'](arg1);
}

export function TestDevice(arg1) {
  return window['go']['main']['App']['TestDevice'](arg1);
}

export function UpdateDevices(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateDevices'](arg1, arg2, arg3);
}
