// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDevice(arg1:string):Promise<main.Device>;

export function GetDevices():Promise<Array<main.Device>>;

export function GetUploadFile():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadDevices():Promise<void>;

export function LoginToDevice(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RefreshDevices():Promise<Array<main.Device>>;

export function RemoveDevice(arg1:string):Promise<void>;

export function SaveDevices():Promise<void>;

export function ScanIPRange(arg1:string,arg2:string):Promise<Array<main.Device>>;

export function SetUploadFile(arg1:string):Promise<string>;

export function TestDevice(arg1:string):Promise<main.Device>;

export function UpdateDevices(arg1:string,arg2:string,arg3:string):Promise<Array<main.UpdateResult>>;
