// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDevice(arg1:string):Promise<main.Device>;

export function BackupDevices(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<Array<main.BackupResult>>;

export function CleanupTempFiles():Promise<void>;

export function ConfigureCamera(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<boolean|string>;

export function ConfigureCameraWithToken(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<boolean|string>;

export function ConfigureCamerasFromData(arg1:Array<main.ExcelRow>,arg2:string,arg3:string,arg4:string,arg5:number):Promise<Array<main.CameraConfigResult>>;

export function GetBackupSettings():Promise<main.BackupSettings>;

export function GetCameraConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.CameraConfig>;

export function GetCameraConfigWithToken(arg1:string,arg2:string,arg3:string):Promise<main.CameraConfig>;

export function GetCameraTasks(arg1:string,arg2:string,arg3:string):Promise<Array<main.Camera>>;

export function GetCameraTasksWithToken(arg1:string,arg2:string):Promise<Array<main.Camera>>;

export function GetDevices():Promise<Array<main.Device>>;

export function GetMd5File():Promise<string>;

export function GetUploadFile():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadDevices():Promise<void>;

export function LoginToDevice(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ParseExcelSheet(arg1:string,arg2:number):Promise<Array<main.ExcelRow>>;

export function ProcessExcelData(arg1:Array<main.ExcelRow>,arg2:string,arg3:string,arg4:string,arg5:number):Promise<Array<main.CameraConfigResult>>;

export function RefreshDevices():Promise<Array<main.Device>>;

export function RemoveDevice(arg1:string):Promise<void>;

export function RestoreDeviceDB(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.RestoreResult>;

export function RestoreDevicesDB(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<Array<main.RestoreResult>>;

export function SaveBackupSettings(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveDevices():Promise<void>;

export function SaveExcelData(arg1:string):Promise<string>;

export function ScanIPRange(arg1:string,arg2:string):Promise<Array<main.Device>>;

export function SelectFolder():Promise<string>;

export function SetCameraIndex(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<boolean|string>;

export function SetCameraIndexWithToken(arg1:string,arg2:string,arg3:string,arg4:number):Promise<boolean|string>;

export function SetMd5File(arg1:string):Promise<string>;

export function SetUploadFile(arg1:string):Promise<string>;

export function SyncDeviceTime(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<main.TimeSyncResult>>;

export function TestDevice(arg1:string):Promise<main.Device>;

export function UpdateDevices(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<main.UpdateResult>>;
