// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDevice(arg1) {
  return window['go']['main']['App']['AddDevice'](arg1);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetUploadFile() {
  return window['go']['main']['App']['GetUploadFile']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadDevices() {
  return window['go']['main']['App']['LoadDevices']();
}

export function LoginToDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoginToDevice'](arg1, arg2, arg3);
}

export function RefreshDevices() {
  return window['go']['main']['App']['RefreshDevices']();
}

export function RemoveDevice(arg1) {
  return window['go']['main']['App']['RemoveDevice'](arg1);
}

export function SaveDevices() {
  return window['go']['main']['App']['SaveDevices']();
}

export function ScanIPRange(arg1, arg2) {
  return window['go']['main']['App']['ScanIPRange'](arg1, arg2);
}

export function SetUploadFile(arg1) {
  return window['go']['main']['App']['SetUploadFile'](arg1);
}

export function TestDevice(arg1) {
  return window['go']['main']['App']['TestDevice'](arg1);
}

export function UpdateDevices(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateDevices'](arg1, arg2, arg3);
}
